### ISSUE TITLE
no function clause matching in Mix.env

### ISSUE THREAD

**Issue by hopewise** [edeliver/edeliver#241]
I am trying to build a release for stating, however, I get this error:

```
    $mix edeliver build release --verbose

.
.
.


** (FunctionClauseError) no function clause matching in Mix.env/1
    (mix) lib/mix.ex:213: Mix.env("prod")
    lib/exrm/utils/utils.ex:19: ReleaseManager.Utils.with_env/2
    lib/mix/tasks/release.ex:164: Mix.Tasks.Release.generate_sys_config/1
    lib/mix/tasks/release.ex:74: Mix.Tasks.Release.do_run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2


A remote command failed on:

  admin@xx.xx.xx.xx

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd /tmp/edeliver/myapp/builds
    if [ "mix" = "rebar" ]; then
      echo "using rebar to generate release"
      ./rebar   -f generate
    elif [ "mix" = "relx" ]; then
      echo "using relx to generate release"
      ./relx release
    elif [ "mix" = "mix" ]; then
      echo "using mix to generate release"
      MIX_ENV="prod" LINK_SYS_CONFIG="" LINK_VM_ARGS="/home/admin/vm.args" APP="my app" AUTO_VERSION="" BRANCH="master" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" USING_DISTILLERY="true" mix  release --verbose --env="prod" --name="my app"
    fi
  

```

Any idea?

**Comment by lukerollans** [comment]
> (mix) lib/mix.ex:213: Mix.env("prod")

`Mix.env/1` is does not accept binaries, only atoms

**Comment by hopewise** [comment]
I removed `exrm` from app's deps and upgraded `distillery`, got it working
