### ISSUE TITLE
Application Starting with error and not showing migration status. 

### ISSUE THREAD

**Issue by edgar971** [edeliver/edeliver#293]
### Environment
* Phoenix version: 1.3.4
* Ecto version: 2.1
* Edeliver version: edeliver v1.4.5
* Elixir version: 1.6.3
* Build tool and version (distillery): distillery v2.0.10
* Operating system (on build / deploy hosts): Ubuntu 16.04.4 x64 
* Are you using an umbrella project (yes|no): yes

### Verbose output

* Are there more information when running with `--verbose`?
* Can you narrow down the code line causing the issue when running with `--debug`?
* Please remove any private data from the output before pasting it here (login credentials, ip addresses user names etc.)

### Current behavior

I'm deploying an umbrella project with the following structure: 
- apps/
-- app_web <--- Phoenix app
-- app <--- Ecto app

When I run `mix edeliver start production` I get an error but the application starts successfully: 
```
-----> starting production servers

production node:

  user    : user
  host    : server-1
  path    : /home/user/apps/app/app_release
  response: ▸  Received 'pang' from app@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
▸  Received 'pang' from app@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
▸  Given the following expression: Elixir.Edeliver.run_command([:monitor_startup_progress, "app", :compact])
▸  The remote call failed with:
▸  ** (exit) :undef
▸      Edeliver.run_command([:monitor_startup_progress, "app", :compact])
▸      (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
▸      (elixir) src/elixir.erl:265: :elixir.eval_forms/4
▸      (elixir) lib/code.ex:590: Code.eval_quoted/3
▸      (kernel) rpc.erl:197: anonymous fn/5 in :rpc.handle_call_call/6


START DONE!
```

Also, I get the following error when trying to get the migrations status on production: `mix edeliver show migrations on production`: 
```
-----> migrationsing production servers

production node:

  user    : app
  host    : server-1
  path    : /home/user/apps/app/app_release
  response: ▸  Given the following expression: Elixir.Edeliver.run_command([:list_pending_migrations, "app", ""])
▸  The remote call failed with:
▸  ** (exit) :undef
▸      Edeliver.run_command([:list_pending_migrations, "app", ""])
▸      (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
▸      (elixir) src/elixir.erl:265: :elixir.eval_forms/4
▸      (elixir) lib/code.ex:590: Code.eval_quoted/3
▸      (kernel) rpc.erl:197: anonymous fn/5 in :rpc.handle_call_call/6
```

### Expected behavior

I expect the application to not start when an error occurs and to show the migration status when calling the command.

**Comment by lessless** [comment]
Hi,

It looks like a configuration issue. Does app correspond to the main app in
the Distillery configuration?

**Comment by lessless** [comment]
Config looks fine.` :undef` error means that Edeliver module is not found, i.e. it's not part of the release.

**Comment by dokicro** [comment]
I am having same issue ...

**Comment by kristofvanwoensel** [comment]
Same issue!

**Comment by lessless** [comment]
hi @kristofvanwoensel are you sure that Edeliver module is the part of the application?  Is there any additional information in the application logs?

**Comment by dokicro** [comment]
My app is under umbrella maybe that helps? And I dont have anything in logs...

Btw. Server starts up and it works but I still get that message...

**Comment by kristofvanwoensel** [comment]
I'm not sure it's the same issue, but I can't even execute the migrations.
....
else # no restart command
      ECTO_REPOSITORY='\''Boomgaard.Repo'\'' bin/boomgaard rpc '\''Elixir.Edeliver.run_command([:migrate, "boomgaard", "Boomgaard.Repo", :up, ])'\''  > >($output_filter_command $output_filter_command_options)
    fi
  '
+ kill -0 20128
+ kill -0 20127
+ sleep 0.5
+ kill -0 20128
+ kill -0 20127
+ sleep 0.5
+ kill -0 20128
+ kill -0 20127
+ sleep 0.5
+ kill -0 20128
+ kill -0 20127
+ sleep 0.5
+ kill -0 20128
+ kill -0 20127
+ sleep 0.5
▸  Given the following expression: Elixir.Edeliver.run_command([:migrate, "boomgaard", "Boomgaard.Repo", :up])
▸  The remote call failed with:
▸  ** (exit) :function_clause
▸      (edeliver) lib/edeliver.ex:52: Edeliver.run_command([:migrate, "boomgaard", "Boomgaard.Repo", :up])
▸      (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
▸      (elixir) src/elixir.erl:265: :elixir.eval_forms/4
▸      (elixir) lib/code.ex:590: Code.eval_quoted/3
▸      (kernel) rpc.erl:197: anonymous fn/5 in :rpc.handle_call_call/6
++ _status_code=1

**Comment by DmitryKK** [comment]
i have same problem:

```
EDELIVER CTI_OMNI WITH VERSION COMMAND

-----> getting release versions from staging servers
-----> Authorizing hosts

staging node:

  user    : app
  host    :  ......
  path    : /home/app
  response: ▸  Given the following expression: Elixir.Edeliver.run_command([:release_version, cti_omni])
▸  The remote call failed with:
▸  ** (exit) {:badmatch, nil}
▸      (edeliver) lib/edeliver.ex:62: Edeliver.run_command/1
▸      (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
▸      (elixir) src/elixir.erl:258: :elixir.eval_forms/4
▸      (elixir) lib/code.ex:590: Code.eval_quoted/3
▸      (kernel) rpc.erl:197: anonymous fn/5 in :rpc.handle_call_call/6

VERSION DONE!
```

**Comment by kreba** [comment]
I'm encountering similar issues as @edgar971 but with a non-umbrella application.

At first I had an `:undef` error when querying my released application. Through a comparison of the compiled release with another app I found out that my OTP application (and all its dependencies) were not included in the release. It puzzled me for quite some time until a dive in the source code of edeliver revealed that the release name (the first argument to `release` in `rel/config.exs`) determines which OTP application will be included in the release. I don't have an umbrella but I had configured a release name that differed from the app name. (I had hoped to be able to deploy multiple instances of my app on the same server that way.)

So I added a `set applications: [:myapp]` instruction to the release configuration. Now I'm seeing the {:badmatch, nil} error @DmitryKK described. It affects all app specific edeliver commands.

My best guess is that the release name is hardwired into many functionalities where an app name would be more appropriate. I can't say for sure, because I'm only a beginner in Elixir deployments.

The discussion in issue #235 seems to be related.

I'll probably end up doing just 1 release and a custom [config provider](https://hexdocs.pm/distillery/config/runtime.html#config-providers) – or just save myself the hassle and deploy the code to a docker container and run it from there (with plain mix).
