### ISSUE TITLE
"--verbosity : Unknown option" mix release error

### ISSUE THREAD

**Issue by outkine** [edeliver/edeliver#300]
Distillery v2.0 [removed](https://github.com/bitwalker/distillery/blob/75f237521b5ccfb16e822b0c098c88f74e2b08ff/docs/upgrading_to_2_0.md#deprecations) the `--verbosity` option, which causes an error when edeliver uses it in the `mix release` command.

### Environment
Erlang/OTP 21 [erts-10.1.3] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]
Elixir 1.7.4 (compiled with Erlang/OTP 20)
distillery v2.0
edeliver v1.4.5
OS: ubuntu 18
umbrella: no

### Verbose output
```
FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd /tmp/edeliver/chicode/builds
    if [ "mix" = "rebar" ]; then
      echo "using rebar to generate release"
      ./rebar   -f generate
    elif [ "mix" = "relx" ]; then
      echo "using relx to generate release"
      ./relx release
    elif [ "mix" = "mix" ]; then
      echo "using mix to generate release"
      MIX_ENV="prod" LINK_SYS_CONFIG="" LINK_VM_ARGS="" APP="chicode" AUTO_VERSION="" BRANCH="master" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" USING_DISTILLERY="" mix  release --verbosity=verbose
    fi
```

The `mix  release --verbosity=verbose` is causing this problem.

**Comment by lessless** [comment]
thanks for reporting @outkine, I'll take a look at it later today

**Comment by outkine** [comment]
update: running `mix release.init` and committing the resulting directory seems to stop the error.

**Comment by albertosramires** [comment]
I'm getting the same exact error and `mix release.init` isn't solving anything. Am I the only one? Seems like this would be an issue for everyone that's using Distillery v2.0

**Comment by dhirajbajaj** [comment]
@outkine your fix not working for me,

> My app: 

```
using >>
{:edeliver, "~> 1.6.0"},
{:distillery, "~> 2.0.14"}

O/P::

Changed release version from 0.1.0 to 0.1.0+508a78a
** (Mix) Could not invoke task "release": 1 error found!
--verbosity : Unknown option

FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd /home/deploy/edeliver/project/builds
    if [ "mix" = "rebar" ]; then
      echo "using rebar to generate release"
      ./rebar   -f generate
    elif [ "mix" = "relx" ]; then
      echo "using relx to generate release"
      ./relx release
    elif [ "mix" = "mix" ]; then
      echo "using mix to generate release"
      MIX_ENV="prod" LINK_SYS_CONFIG="" LINK_VM_ARGS="" APP="elixirum" AUTO_VERSION="revision" BRANCH="master" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" USING_DISTILLERY="" mix do release.version  --verbose,  release --verbosity=normal
    fi
```

**Comment by Yamilquery** [comment]
I update `edeliver` and `distillery` deps and I get the following error:

```
Generated rigging app
** (UndefinedFunctionError) function Mix.Releases.Config.get/1 is undefined (module Mix.Releases.Config is not available)
    Mix.Releases.Config.get([executable: [enabled: false, transient: false], is_upgrade: false, no_tar: false, selected_environment: :default, selected_release: :default, upgrade_from: :latest, verbosity: :normal])
    lib/distillery/tasks/release.ex:94: Mix.Tasks.Release.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

**Comment by Faymir** [comment]
Hello,
I go the same problem as @dhirajbajaj 
Running `mix release.init` didn't solve the problem.
Please halp! 
I am on 
+ Elixir 1.9
+ Phoenix 1.4
+ edeliver 1.7.0
+ distillery 2.1.1

the error message is show as below

```elixir
using mix to generate release
** (Mix) Could not invoke task "distillery.release": 1 error found!
--verbosity : Unknown option

A remote command failed on:

 user@server

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd /fake/path/to/app_build
    if [ "mix" = "rebar" ]; then
      echo "using rebar to generate release"
      ./rebar   -f generate
    elif [ "mix" = "relx" ]; then
      echo "using relx to generate release"
      ./relx release
    elif [ "mix" = "mix" ]; then
      echo "using mix to generate release"
      MIX_ENV="prod" LINK_SYS_CONFIG="" LINK_VM_ARGS="" APP="myapp" AUTO_VERSION="" BRANCH="master" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" USING_DISTILLERY="" mix  distillery.release --verbosity=verbose
    fi
  ```

**Comment by bendyorke** [comment]
I had the same problem, matching my local and prod elixir versions did not fix it, neither did changing `edeliver` and `distillery` versions, nor did running `mix release.init`. I eventually fixed it by running:

```
$ mix distillery.init
```

And committing the files
