### ISSUE TITLE
Please update documentation with how to use edeliver with Mix releases. It only talks about distillery

### ISSUE THREAD

**Issue by theagilecoder** [edeliver/edeliver#322]
Please update documentation with how to use edeliver with Mix releases. It only talks about distillery

**Comment by grufino** [comment]
Is it possible tho? I am trying to change my deploy scripts to remove distillery entirely, and after removing the dependency, edeliver not even compiles... still debugging tho...

```
== Compilation error in file lib/distillery/plugins/modify_relup.ex ==
** (CompileError) lib/distillery/plugins/modify_relup.ex:15: module Distillery.Releases.Plugin is not loaded and could not be found
    (elixir 1.10.1) expanding macro: Kernel.use/1
    lib/distillery/plugins/modify_relup.ex:15: Releases.Plugin.ModifyRelup (module)
could not compile dependency :edeliver, "mix compile" failed. You can recompile this dependency with "mix deps.compile edeliver", update it with "mix deps.update edeliver" or clean it with "mix deps.clean edeliver"
```

**Comment by lessless** [comment]
I will be happy to review PR if anyone would love to work on native Elixir releases compatibility.

**Comment by marekciupak** [comment]
I just wanted to confirm what @grufino wrote.

I've just created a new application from scratch and configured mix releases and added edeliver without distillery. I've received a similar error:

```
== Compilation error in file lib/distillery/plugins/link_config.ex ==
** (CompileError) lib/distillery/plugins/link_config.ex:17: module Distillery.Releases.Plugin is not loaded and could not be found
    (elixir 1.10.2) expanding macro: Kernel.use/1
    lib/distillery/plugins/link_config.ex:17: Releases.Plugin.LinkConfig (module)
could not compile dependency :edeliver, "mix compile" failed. You can recompile this dependency with "mix deps.compile edeliver", update it with "mix deps.update edeliver" or clean it with "mix deps.clean edeliver"
```

**Comment by dev-cyprium** [comment]
I've decided to try to integrate this as the fix seems pretty straightforward.
The error you're getting has to deal with `optional: true` dep set to `distilery` in the `mix.exs` file of the `edeliver` project.

Adding:
```elixir
if Code.ensure_loaded?(Distillery.Releases.Plugin) do
  defmodule Releases.Plugin.ModifyRelup do
  end
end
```

Makes your error go away. As for supporting `mix release` I'm looking into creating a pull request for this in a day or two as this seems like a really easy addition to add :)
